ALTER TABLE `table3` DROP FOREIGN KEY `testfk`;
ALTER TABLE `table2` DROP FOREIGN KEY `table2_FK_COL_FK_1_COL_FK_2_table1`;
DROP TABLE IF EXISTS `table3`;
DROP TABLE IF EXISTS `table2`;
DROP TABLE IF EXISTS `table1`;
CREATE TABLE `table1`
(
    `COL_PK_1`    VARCHAR(32) NOT NULL,
    `COL_PK_2`    INTEGER,
    `COL_INDEX_1` BINARY(100) NOT NULL,
    `COL_INDEX_2` DOUBLE NOT NULL,
    `COL_INDEX_3` CHAR(4) NULL,
    PRIMARY KEY (`COL_PK_1`, `COL_PK_2`)
);
CREATE INDEX `testindex1` ON `table1` (`COL_INDEX_2`);
CREATE UNIQUE INDEX `testindex2` ON `table1` (`COL_INDEX_3`, `COL_INDEX_1`);
CREATE TABLE `table2`
(
    `COL_PK`   INTEGER,
    `COL_FK_1` INTEGER,
    `COL_FK_2` VARCHAR(32) NOT NULL,
    PRIMARY KEY (`COL_PK`)
);
CREATE TABLE `table3`
(
    `COL_PK` VARCHAR(16) NULL,
    `COL_FK` INTEGER NOT NULL,
    PRIMARY KEY (`COL_PK`)
);
ALTER TABLE `table2` ADD CONSTRAINT `table2_FK_COL_FK_1_COL_FK_2_table1` FOREIGN KEY (`COL_FK_1`, `COL_FK_2`) REFERENCES `table1` (`COL_PK_2`, `COL_PK_1`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `table3` ADD CONSTRAINT `testfk` FOREIGN KEY (`COL_FK`) REFERENCES `table2` (`COL_PK`) ON DELETE NO ACTION ON UPDATE NO ACTION;
